backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Weekly Overview"
    name: "weekly"
    folder: "src/posts/weekly"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Ed Blackwood" }
      - { label: "Week Start Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          - { label: "Bible Reading", value: "Bible Reading" }
          - { label: "Worship", value: "Worship" }
          - { label: "Prayer", value: "Prayer" }
          - { label: "Family Worship", value: "Family Worship" }
          - { label: "Old Testament", value: "Old Testament" }
          - { label: "New Testament", value: "New Testament" }
          - { label: "Church History", value: "Church History" }
      - { label: "Type", name: "type", widget: "hidden", default: "weekly" }

  - label: "Daily Notes"
    name: "daily"
    folder: "src/posts/daily"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Ed Blackwood" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Related Weekly Post", name: "weekly_post", widget: "relation", collection: "weekly", search_fields: ["title"], value_field: "{{slug}}", display_fields: ["title"] }
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          - { label: "Bible Reading", value: "Bible Reading" }
          - { label: "Worship", value: "Worship" }
          - { label: "Prayer", value: "Prayer" }
          - { label: "Family Worship", value: "Family Worship" }
          - { label: "Old Testament", value: "Old Testament" }
          - { label: "New Testament", value: "New Testament" }
          - { label: "Church History", value: "Church History" }
          - { label: "Genesis", value: "Genesis" }
          - { label: "Exodus", value: "Exodus" }
          - { label: "Leviticus", value: "Leviticus" }
          - { label: "Numbers", value: "Numbers" }
          - { label: "Deuteronomy", value: "Deuteronomy" }
          - { label: "Joshua", value: "Joshua" }
          - { label: "Judges", value: "Judges" }
          - { label: "Ruth", value: "Ruth" }
          - { label: "1 Samuel", value: "1 Samuel" }
          - { label: "2 Samuel", value: "2 Samuel" }
          - { label: "1 Kings", value: "1 Kings" }
          - { label: "2 Kings", value: "2 Kings" }
          - { label: "1 Chronicles", value: "1 Chronicles" }
          - { label: "2 Chronicles", value: "2 Chronicles" }
          - { label: "Ezra", value: "Ezra" }
          - { label: "Nehemiah", value: "Nehemiah" }
          - { label: "Esther", value: "Esther" }
          - { label: "Job", value: "Job" }
          - { label: "Psalms", value: "Psalms" }
          - { label: "Proverbs", value: "Proverbs" }
          - { label: "Ecclesiastes", value: "Ecclesiastes" }
          - { label: "Song of Solomon", value: "Song of Solomon" }
          - { label: "Isaiah", value: "Isaiah" }
          - { label: "Jeremiah", value: "Jeremiah" }
          - { label: "Lamentations", value: "Lamentations" }
          - { label: "Ezekiel", value: "Ezekiel" }
          - { label: "Daniel", value: "Daniel" }
          - { label: "Hosea", value: "Hosea" }
          - { label: "Joel", value: "Joel" }
          - { label: "Amos", value: "Amos" }
          - { label: "Obadiah", value: "Obadiah" }
          - { label: "Jonah", value: "Jonah" }
          - { label: "Micah", value: "Micah" }
          - { label: "Nahum", value: "Nahum" }
          - { label: "Habakkuk", value: "Habakkuk" }
          - { label: "Zephaniah", value: "Zephaniah" }
          - { label: "Haggai", value: "Haggai" }
          - { label: "Zechariah", value: "Zechariah" }
          - { label: "Malachi", value: "Malachi" }
          - { label: "Matthew", value: "Matthew" }
          - { label: "Mark", value: "Mark" }
          - { label: "Luke", value: "Luke" }
          - { label: "John", value: "John" }
          - { label: "Acts", value: "Acts" }
          - { label: "Romans", value: "Romans" }
          - { label: "1 Corinthians", value: "1 Corinthians" }
          - { label: "2 Corinthians", value: "2 Corinthians" }
          - { label: "Galatians", value: "Galatians" }
          - { label: "Ephesians", value: "Ephesians" }
          - { label: "Philippians", value: "Philippians" }
          - { label: "Colossians", value: "Colossians" }
          - { label: "1 Thessalonians", value: "1 Thessalonians" }
          - { label: "2 Thessalonians", value: "2 Thessalonians" }
          - { label: "1 Timothy", value: "1 Timothy" }
          - { label: "2 Timothy", value: "2 Timothy" }
          - { label: "Titus", value: "Titus" }
          - { label: "Philemon", value: "Philemon" }
          - { label: "Hebrews", value: "Hebrews" }
          - { label: "James", value: "James" }
          - { label: "1 Peter", value: "1 Peter" }
          - { label: "2 Peter", value: "2 Peter" }
          - { label: "1 John", value: "1 John" }
          - { label: "2 John", value: "2 John" }
          - { label: "3 John", value: "3 John" }
          - { label: "Jude", value: "Jude" }
          - { label: "Revelation", value: "Revelation" }

      - { label: "Type", name: "type", widget: "hidden", default: "daily" }

  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "About Page"
        name: "about"
        file: "src/about.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Path", name: "path", widget: "hidden", default: "about" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/about/" }
          - { label: "Content", name: "body", widget: "markdown" }

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Site Settings"
        name: "site"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Site Name", name: "name", widget: "string" }
          - { label: "Site Author", name: "author", widget: "string" }
          - { label: "Site URL", name: "url", widget: "string" }
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Background Image", name: "image", widget: "image" }

      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: "Nav Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
